"""YAML configuration loading with defaults and validation."""

import os
import yaml

DEFAULTS = {
    "slurm": {
        "template": "",          # Path to existing sbatch script (overrides below)
        "partition": "compute",
        "nodes": 1,
        "ntasks_per_node": 32,
        "time": "24:00:00",
        "job_name_prefix": "vasp",
        "extra": "",
    },
    "vasp": {
        "exec": "vasp_std",
    },
    "work_dir": "./",
    "poll_interval": 60,
    "mode": "sequential",  # sequential | chain
    # ---- 输入文件自动生成 ----
    "potcar": {
        "auto_generate": True,  # 自动用 vaspkit 103 生成 POTCAR
    },
    "kpoints": {
        "auto_generate": True,  # 自动生成 KPOINTS
        "mode": "direct",       # direct=直接写入 | vaspkit=用vaspkit 102
        "scheme": "M",          # G=Gamma-centered | M=Monkhorst-Pack
        "mesh": [0, 0, 0],     # [kx, ky, kz], 0=自动用kpoints_density算
        "kpoints_density": 0.04, # K点密度 (每埃^-1)
    },
    # ---- 断点续算 ----
    "resume": {
        "skip_completed": True,   # 跳过已完成步骤
        "retry_failed": True,     # 失败步骤自动重试
        "max_retries": 1,         # 每步最大重试次数
    },
    "steps": {
        "opt": {
            "enabled": True,
            "job_name": "opt",
            "dir": "opt",
            "incar": {
                "ISIF": 3,
                "IBRION": 2,
                "NSW": 100,
                "EDIFF": 1e-6,
                "EDIFFG": -0.02,
                "ENCUT": 520,
                "ISMEAR": 0,
                "SIGMA": 0.05,
                "PREC": "Normal",
                "LREAL": "Auto",
                "LWAVE": False,
                "LCHARG": True,
            },
        },
        "scf": {
            "enabled": True,
            "job_name": "scf",
            "dir": "scf",
            "incar": {
                "NSW": 0,
                "ICHARG": 2,
                "EDIFF": 1e-6,
                "ENCUT": 520,
                "ISMEAR": 0,
                "SIGMA": 0.05,
                "PREC": "Normal",
                "LREAL": "Auto",
                "LWAVE": False,
                "LCHARG": True,
                "LAECHG": True,
            },
        },
        "dos": {
            "enabled": True,
            "job_name": "dos",
            "dir": "dos",
            "incar": {
                "NSW": 0,
                "ICHARG": 11,
                "ISMEAR": -5,
                "SIGMA": 0.05,
                "ENCUT": 520,
                "PREC": "Normal",
                "LREAL": "Auto",
                "LORBIT": 11,
                "LWAVE": False,
                "LCHARG": False,
                "NEDOS": 2000,
            },
        },
    },
    "postprocess": {
        "vaspkit_tasks": [],
    },
}


def _deep_merge(base, override):
    """Recursively merge override into base dict."""
    for key, value in override.items():
        if key in base and isinstance(base[key], dict) and isinstance(value, dict):
            _deep_merge(base[key], value)
        else:
            base[key] = value


def load_config(config_path: str) -> dict:
    """Load YAML config file and merge with defaults.

    Args:
        config_path: Path to YAML config file.

    Returns:
        Merged configuration dictionary.
    """
    with open(config_path, "r") as f:
        user_config = yaml.safe_load(f)

    merged = DEFAULTS.copy()
    _deep_merge(merged, user_config)

    merged["work_dir"] = os.path.abspath(merged["work_dir"])

    return merged


def validate_config(cfg: dict) -> list[str]:
    """Validate configuration and return list of warnings/errors."""
    issues = []

    # Check vasp exec
    vasp_exec = cfg["vasp"]["exec"]
    if vasp_exec not in ("vasp_std", "vasp_gam", "vasp_ncl", "qvasp"):
        issues.append(f"Unusual VASP exec '{vasp_exec}', make sure it exists in PATH")

    # Check if work_dir exists
    if not os.path.isdir(cfg["work_dir"]):
        issues.append(f"Work directory '{cfg['work_dir']}' does not exist")

    # Check mode
    if cfg["mode"] not in ("sequential", "chain"):
        issues.append(f"Mode '{cfg['mode']}' invalid, use 'sequential' or 'chain'")

    # Check required INCAR tags for opt
    opt_incar = cfg["steps"]["opt"]["incar"]
    if opt_incar.get("ISIF", 0) not in (2, 3, 4):
        issues.append("opt ISIF should be 2, 3, or 4 for structure optimization")

    # Check required INCAR tags for DOS
    dos_incar = cfg["steps"]["dos"]["incar"]
    if dos_incar.get("ICHARG") != 11:
        issues.append("dos ICHARG should be 11 for non-self-consistent DOS")

    return issues


def write_incar(path: str, incar_params: dict):
    """Write INCAR file from parameter dict.

    Args:
        path: Output INCAR file path.
        incar_params: Dict of INCAR tag -> value.
    """
    lines = ["! INCAR generated by vasp_auto"]
    for tag, value in incar_params.items():
        if isinstance(value, bool):
            value = ".TRUE." if value else ".FALSE."
        elif isinstance(value, float):
            value = f"{value:.6g}"
        lines.append(f"  {tag} = {value}")

    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


def write_kpoints(
    path: str,
    scheme: str = "M",
    mesh: list = None,
    kpoints_density: float = 0.04,
    poscar_path: str = None,
):
    """Write KPOINTS file.

    If mesh is [0,0,0] and poscar_path is given, auto-calculate mesh
    from lattice vectors and kpoints_density. Otherwise write the mesh directly.

    Args:
        path: Output KPOINTS file path.
        scheme: 'G' for Gamma-centered, 'M' for Monkhorst-Pack.
        mesh: [kx, ky, kz]. Use [0,0,0] to auto-calculate from density.
        kpoints_density: Points per inverse Angstrom.
        poscar_path: Path to POSCAR for auto mesh calculation.
    """
    if mesh is None:
        mesh = [0, 0, 0]

    # Auto-calculate k-mesh from lattice vectors
    if mesh == [0, 0, 0] and poscar_path and os.path.isfile(poscar_path):
        mesh = _auto_kmesh(poscar_path, kpoints_density)

    header = f"KPOINTS generated by vasp_auto: {scheme}-centered {mesh[0]}x{mesh[1]}x{mesh[2]}"
    lines = [
        header,
        "0",
        "Gamma" if scheme.upper() == "G" else "Monkhorst-Pack",
        f"  {mesh[0]}  {mesh[1]}  {mesh[2]}",
        "  0.0  0.0  0.0",
    ]

    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


def _auto_kmesh(poscar_path: str, density: float) -> list[int]:
    """Calculate k-point mesh from POSCAR lattice vectors and desired density.

    Uses the formula: N_i = max(1, ceil(|b_i| / density))
    where b_i is the i-th reciprocal lattice vector length.
    """
    try:
        with open(poscar_path, "r") as f:
            lines = f.readlines()
    except OSError:
        return [1, 1, 1]

    # POSCAR: line 0 = comment, line 1 = scale, lines 2-4 = lattice vectors
    if len(lines) < 5:
        return [1, 1, 1]

    scale = float(lines[1].strip())
    vectors = []
    for i in range(2, 5):
        parts = lines[i].strip().split()
        v = [float(x) * scale for x in parts[:3]]
        vectors.append(v)

    # Compute reciprocal vectors: b_i = 2pi * (a_j x a_k) / (a_i . (a_j x a_k))
    import math

    a1, a2, a3 = vectors

    def cross(u, v):
        return [
            u[1] * v[2] - u[2] * v[1],
            u[2] * v[0] - u[0] * v[2],
            u[0] * v[1] - u[1] * v[0],
        ]

    def dot(u, v):
        return u[0] * v[0] + u[1] * v[1] + u[2] * v[2]

    def norm(u):
        return math.sqrt(u[0] ** 2 + u[1] ** 2 + u[2] ** 2)

    volume = dot(a1, cross(a2, a3))
    if abs(volume) < 1e-12:
        return [1, 1, 1]

    b1 = [2 * math.pi * x / volume for x in cross(a2, a3)]
    b2 = [2 * math.pi * x / volume for x in cross(a3, a1)]
    b3 = [2 * math.pi * x / volume for x in cross(a1, a2)]

    mesh = []
    for b in [b1, b2, b3]:
        n = max(1, int(math.ceil(norm(b) / density)))
        mesh.append(n)

    return mesh
